version: '3.7'
services:
  jenkins:
    image: devops-culture/jenkins-docker:1
    privileged: true
    container_name: jenkins-docker
    ports:
      - 8081:8080
      - 50000:50000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/jenkins_home:/var/jenkins_home
  jenkins-ddclient:
    image: 'linuxserver/ddclient'
    environment:
      PUID: '0'
      PGID: '0'
      TZ: 'America/Chicago'
    volumes:
      - '/tmp/ddclient-config:/config'
      - './ddclient.conf:/config/ddclient.conf'