version: '3.7'
services:
  jenkins:
    image: devops-culture/jenkins-docker:1
    container_name: jenkins-docker
    ports:
      - 8081:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/jenkins_home:/var/jenkins_home